### ISSUE TITLE
Install torch-cluster for C++ 

### ISSUE THREAD

**Issue by AmadouTidjani** [rusty1s/pytorch_cluster#184]
Is torch-cluster available in C++ ? I am trying to install torch and torch-cluster in C++ following your ReadMe, but It's just torch. How can I install torch-cluster ?
Thanks in advance!

**Comment by rusty1s** [comment]
What do you mean it is just for `torch`? The [README](https://github.com/rusty1s/pytorch_cluster#c-api) instructions should work. [Here](https://github.com/pyg-team/pytorch_geometric/tree/master/examples/cpp) is a more detailed example (on `torch-scatter`/`torch-sparse` rather than `torch-cluster` though).

**Comment by AmadouTidjani** [comment]
What I meant was that, following your instructions, I was able to install torch properly. But I couldn't use torch-cluster functions like fps or radius. 
So I'm wondering about the installation of torch-cluster in C++.

for example in python, once torch-cluster is installed, I can call the functions as follows "from torch_cluster import fps, radius". I need to do the same in C++.

Thanks

**Comment by rusty1s** [comment]
[Here](https://github.com/rusty1s/pytorch_cluster/blob/master/csrc/cluster.h) are the function we expose as part of C++

**Comment by AmadouTidjani** [comment]
I was able to use the C++ code in the [@csrc](https://github.com/rusty1s/pytorch_cluster/tree/master/csrc) folder directly. Thanks
