### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by cxw-droid** [rusty1s/pytorch_cluster#192]
Hi, is there any document for `pytorch_cluster`? E.g., I found there are two `random_walk` functions, one in `pytorch_cluster` and another in `pytorch_sparse`, and realized they are different. I am also not clear how many function are already implemented in this package so they can be directedly called by users. Is there any such document? Thanks.

**Comment by rusty1s** [comment]
We haven't set up documentation for `torch-cluster`, sorry :( We got a bit lazy here. Most of the functions like `graclus`, `fps`, `knn`, etc are documented directly in PyG, see https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#pooling-layers. Alternatively, functions should be documented in the source code as well.

You are right that `torch-sparse` also has a `random_walk` implementation (cannot really remember the reason why), but the one in `torch-cluster` is much more advanced since it integrates `Node2Vec`-like random walk sampling.
