### ISSUE TITLE
import error from torch_cluster import neighbor_sampler

### ISSUE THREAD

**Issue by aditikulkerni** [rusty1s/pytorch_cluster#47]
Hi, I just updated torch_geometric and torch_cluster to latest versions. However I am getting an error while importing neighbor_sampler.
/torch_geometric/data/sampler.py calls neighbor_sampler which is no more there in torch_cluster.
What versions should I use here?

**Comment by rusty1s** [comment]
I am not sure whats causing this. We did not remove anything from torch-cluster.

**Comment by aditikulkerni** [comment]
So, if I do 
`from torch_cluster import neighbor_sampler`
I get an error because now you have sample.py I guess instead of neighbor_sampler.
Is it correct?

**Comment by rusty1s** [comment]
Not really, see [here](https://github.com/rusty1s/pytorch_cluster/blob/master/torch_cluster/__init__.py).

**Comment by aditikulkerni** [comment]
I downgraded torch-geometric to v1.0.3 and it worked, however, I can not use SAGPooling unless I have torch-geometric v1.3. What should be torch_cluster version for torch-geometric v1.3?

**Comment by rusty1s** [comment]
You need at least version torch-cluster==1.4.4 with PyTorch 1.2 and torch-cluster==1.4.5 with Pytorch>=1.3.

**Comment by jfchow-blow** [comment]
Hi, I just came across a problem when using the NeighborSampler API. When the augmentation size=1, the graph will not be sampled. Instead, it will output the origin graph. Here is my code for testing this issue:

import torch
import torch_geometric.utils as tu
import torch_geometric.data as tgd
import networkx.generators.stochastic as sg
from torch_geometric.utils.repeat import repeat
from torch_cluster import neighbor_sampler

data = torch.load('Commuting_network.pt')
sampler = tgd.NeighborSampler(data, 
                              size=1.0, 
                              num_hops=1,
                              batch_size=1,
                              flow='target_to_source',
                              bipartite=False)
print(data)    
for subdata in sampler(torch.tensor([0])):
    print(subdata.e_id)

the output is:
Data(edge_attr=[3844, 2], edge_index=[2, 3844], x=[62, 3], y=[3844, 1])
tensor([ 7, 47, 31, 57, 45, 58, 29,  4,  0, 15, 53, 33, 48,  3, 11, 40, 23, 52,
        17, 37, 27,  1, 12, 60, 19,  6, 10,  2, 54, 38, 56, 51, 21, 35, 13, 46,
         8, 30,  9, 59, 50, 28, 39, 44, 43, 36, 25, 41,  5, 16, 55, 26, 18, 22,
        61, 20, 42, 24, 49, 14, 34, 32])

The input data is a fully connected graph with 62 nodes. As we can see that the size of the output e_id is 62 instead of 1. Did I apply this method wrong?  Thanks for your time reading this.
